# Generated by Django 5.0.6 on 2024-05-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('use_cache', models.BooleanField(default=False, verbose_name='Use Cache')),
                ('cache_time', models.IntegerField(default=0, verbose_name='Cache Time')),
                ('authorization_required', models.BooleanField(default=False, verbose_name='Authorization Required')),
                ('permission_required', models.BooleanField(default=False, verbose_name='Permission Required')),
                ('add_view', models.BooleanField(default=False, verbose_name='Add View')),
                ('list_view', models.BooleanField(default=False, verbose_name='List View')),
                ('detail_view', models.BooleanField(default=False, verbose_name='Detail View')),
                ('update_view', models.BooleanField(default=False, verbose_name='Update View')),
                ('delete_view', models.BooleanField(default=False, verbose_name='Delete View')),
                ('pagination', models.BooleanField(default=False, verbose_name='Pagination')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('throttle', models.BooleanField(default=False, verbose_name='Throttle')),
                ('throttle_time', models.IntegerField(default=0, verbose_name='Throttle')),
            ],
            options={
                'verbose_name': 'Generic API',
                'verbose_name_plural': 'Generic API',
            },
        ),
        migrations.CreateModel(
            name='GenericAPIField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Field name')),
                ('field_type', models.CharField(choices=[('char', 'Text field'), ('text', 'Big text field'), ('text_with_ckeditor', 'Big text field with ckeditor'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('file', 'File'), ('image', 'Image'), ('image_compressed', 'Image compressed'), ('url', 'URL'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('email', 'Email'), ('phone_number', 'Phone Number'), ('slug', 'Slug')], max_length=255, verbose_name='Field type')),
                ('is_searchable', models.BooleanField(default=False, verbose_name='Is Searchable')),
                ('is_filterable', models.BooleanField(default=False, verbose_name='Is Filterable')),
                ('is_hidden_for_admin', models.BooleanField(default=False, verbose_name='Is Hidden for Admin')),
                ('is_lookup', models.BooleanField(default=False, verbose_name='Is Lookup')),
            ],
        ),
    ]
