# Generated by Django 5.0.6 on 2024-05-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericapi',
            name='counter',
            field=models.BooleanField(default=False, verbose_name='Counter'),
        ),
    ]
