# Generated by Django 5.0.6 on 2024-05-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_alter_genericapi_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericapifield',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.genericapi'),
        ),
        migrations.AlterField(
            model_name='genericapi',
            name='throttle_time',
            field=models.IntegerField(default=0, verbose_name='Throttle time'),
        ),
    ]
